### ISSUE TITLE
Project license 

### ISSUE THREAD

**Issue by saloid** [rolohaun/Rook#3]
Hi.
Put your projects license file in root folder, or write about it somewhere in readme please.
Is it allowed for commercial use?
Thanks

**Comment by rolohaun** [comment]
I believe by default without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

If you want to use it for commercial us I would suggest you subscribe to my patreon tier

**Comment by ebod** [comment]
Unfortunately, default copyright applies to both commercial and non-commercial use. Building one of these printers for private use might already be copyright infringement and forking this repository and making a mod probably also require explicit permissions.

Even if this is your intention, you should write it down to make it clear.

If you want to allow derivate works and want to exclude commercial use, you could use a [cc-by-sa-nc](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

**Comment by saloid** [comment]
Thanks for adding license file! So now issue resolved
